[project]
name = "specrec"
version = "0.1.0"
description = "The program for the analysis of low-energy ions scattering spectroscopy data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "requests>=2.32.3",
]
